const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

const questions = [
  // ─── FRONTEND ────────────────────────────────────────────────────────────────
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Beginner', type: 'mcq', question: 'Which CSS property is used to make a flex container?', options: ['display: flex', 'flex: 1', 'flexbox: true', 'layout: flex'], answer: 'display: flex' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does the `useState` hook return in React?', options: ['A single state value', 'An array with state value and setter function', 'An object with state and dispatch', 'A promise'], answer: 'An array with state value and setter function' },
  { domain: 'Frontend', category: 'HTML', phase: 1, level: 'Beginner', type: 'mcq', question: 'Which HTML tag is used for the largest heading?', options: ['<h6>', '<h1>', '<heading>', '<header>'], answer: '<h1>' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the correct CSS to make text bold?', options: ['font-weight: bold', 'text-bold: true', 'font: bold', 'bold: true'], answer: 'font-weight: bold' },
  { domain: 'Frontend', category: 'JavaScript', phase: 1, level: 'Beginner', type: 'mcq', question: 'Which event fires when a user clicks an element?', options: ['onhover', 'onclick', 'onpress', 'ontap'], answer: 'onclick' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does `box-sizing: border-box` do?', options: ['Adds a border automatically', 'Includes padding and border in the element width', 'Creates a box shadow', 'Sets box dimensions'], answer: 'Includes padding and border in the element width' },
  { domain: 'Frontend', category: 'HTML', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the purpose of the `alt` attribute in an `<img>` tag?', options: ['Alternative image source', 'Alternative text if image cannot be displayed', 'Image title tooltip', 'Image alignment'], answer: 'Alternative text if image cannot be displayed' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Beginner', type: 'mcq', question: 'Which CSS value makes an element invisible but still takes space?', options: ['display: none', 'visibility: hidden', 'opacity: 0', 'hidden: true'], answer: 'visibility: hidden' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the Virtual DOM in React?', options: ['The actual browser DOM', 'A lightweight JavaScript representation of the real DOM', 'A virtual reality interface', 'Server-side rendering technology'], answer: 'A lightweight JavaScript representation of the real DOM' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What hook would you use to perform side effects in React?', options: ['useState', 'useEffect', 'useContext', 'useMemo'], answer: 'useEffect' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is CSS specificity?', options: ['Speed of CSS rendering', 'The priority system determining which CSS rules apply', 'Number of CSS rules', 'Browser compatibility score'], answer: 'The priority system determining which CSS rules apply' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a CSS pseudo-class?', options: ['A fake CSS class', 'A keyword added to a selector specifying a special state', 'A CSS variable', 'A class with no styles'], answer: 'A keyword added to a selector specifying a special state' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is code splitting in the context of React?', options: ['Splitting code into multiple files manually', 'Breaking your bundle into smaller chunks loaded on demand', 'Separating HTML, CSS, and JS', 'Using multiple React versions'], answer: 'Breaking your bundle into smaller chunks loaded on demand' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Intermediate', type: 'mcq', question: 'Which hook prevents unnecessary re-renders by memoizing a function?', options: ['useCallback', 'useMemo', 'useRef', 'useEffect'], answer: 'useCallback' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the purpose of React.memo()?', options: ['Memoizes the return value of a function', 'Prevents re-rendering if props have not changed', 'Creates a memoized state variable', 'Caches API calls'], answer: 'Prevents re-rendering if props have not changed' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the difference between controlled and uncontrolled components in React?', options: ['Controlled use refs, uncontrolled use state', 'Controlled have their value driven by React state, uncontrolled manage their own state via the DOM', 'Controlled are class components, uncontrolled are functional', 'No real difference'], answer: 'Controlled have their value driven by React state, uncontrolled manage their own state via the DOM' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is CSS-in-JS?', options: ['Writing CSS inside JavaScript files using libraries like styled-components', 'Converting JavaScript to CSS', 'Inline styles only', 'A CSS preprocessor'], answer: 'Writing CSS inside JavaScript files using libraries like styled-components' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the Flux architecture pattern?', options: ['A CSS layout method', 'A unidirectional data flow pattern used in React apps', 'A HTTP request library', 'A build tool'], answer: 'A unidirectional data flow pattern used in React apps' },
  { domain: 'Frontend', category: 'JavaScript', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is tree shaking in bundlers?', options: ['Removing dead code from the final bundle', 'Building a component tree', 'Traversing the DOM tree', 'A debugging technique'], answer: 'Removing dead code from the final bundle' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does `position: absolute` do in CSS?', options: ['Fixes element to viewport', 'Positions element relative to its nearest positioned ancestor', 'Removes element from flow relative to body', 'Makes element sticky'], answer: 'Positions element relative to its nearest positioned ancestor' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a CSS Grid?', options: ['A CSS table replacement', 'A 2D CSS layout system using rows and columns', 'A grid-based CSS framework', 'A flexbox extension'], answer: 'A 2D CSS layout system using rows and columns' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the purpose of React Concurrent Mode?', options: ['Running React on multiple CPUs', 'Allowing React to interrupt rendering to handle higher-priority updates for a more responsive UI', 'Multi-threading in React', 'Parallel component rendering'], answer: 'Allowing React to interrupt rendering to handle higher-priority updates for a more responsive UI' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is hydration in SSR?', options: ['Adding water to components', 'The process of attaching React event handlers to server-rendered HTML', 'Loading data into components', 'Refreshing the page'], answer: 'The process of attaching React event handlers to server-rendered HTML' },
  { domain: 'Frontend', category: 'React', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of the `key` prop in React lists?', options: ['Styling list items', 'Helping React identify which items have changed, been added, or removed', 'Sorting list items', 'Accessing list items by index'], answer: 'Helping React identify which items have changed, been added, or removed' },
  { domain: 'Frontend', category: 'CSS', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does the CSS `z-index` property control?', options: ['Horizontal position', 'Vertical position', 'The stacking order of overlapping elements', 'Element transparency'], answer: 'The stacking order of overlapping elements' },

  // ─── BACKEND ─────────────────────────────────────────────────────────────────
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does REST stand for?', options: ['Remote Execution State Transfer', 'Representational State Transfer', 'Reliable State Transport', 'Remote State Transfer'], answer: 'Representational State Transfer' },
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Beginner', type: 'mcq', question: 'Which HTTP method is used to retrieve data?', options: ['POST', 'PUT', 'GET', 'DELETE'], answer: 'GET' },
  { domain: 'Backend', category: 'Node.js', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a middleware in Express.js?', options: ['A database connector', 'A function that has access to request, response, and next function', 'A route handler', 'A template engine'], answer: 'A function that has access to request, response, and next function' },
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Beginner', type: 'mcq', question: 'What HTTP status code indicates a successful POST request that created a resource?', options: ['200', '201', '204', '301'], answer: '201' },
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is JSON?', options: ['JavaScript Object Notation — a lightweight data interchange format', 'A JavaScript framework', 'A database type', 'A server language'], answer: 'JavaScript Object Notation — a lightweight data interchange format' },
  { domain: 'Backend', category: 'Node.js', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is an environment variable?', options: ['A variable in your CSS', 'A dynamic value set outside the application code', 'A global JavaScript variable', 'A database variable'], answer: 'A dynamic value set outside the application code' },
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does CORS stand for?', options: ['Cross-Origin Resource Sharing', 'Client-Origin Request Service', 'Cross-Origin Request Service', 'Client-Oriented Resource Sharing'], answer: 'Cross-Origin Resource Sharing' },
  { domain: 'Backend', category: 'Security', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is JWT?', options: ['A JSON database', 'JSON Web Token — a compact URL-safe token for transmitting claims', 'A JavaScript testing tool', 'A Java web framework'], answer: 'JSON Web Token — a compact URL-safe token for transmitting claims' },
  { domain: 'Backend', category: 'Node.js', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the event loop in Node.js?', options: ['A loop for handling HTTP requests', 'The mechanism that allows Node.js to perform non-blocking I/O operations', 'A for loop wrapper', 'A database query loop'], answer: 'The mechanism that allows Node.js to perform non-blocking I/O operations' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is database indexing?', options: ['Numbering database rows', 'A data structure that improves query speed at the cost of storage', 'Backing up a database', 'Sorting database records'], answer: 'A data structure that improves query speed at the cost of storage' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is connection pooling?', options: ['Reusing database connections instead of opening a new one for each request', 'Combining multiple databases', 'A load balancing technique', 'Caching query results'], answer: 'Reusing database connections instead of opening a new one for each request' },
  { domain: 'Backend', category: 'Security', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of bcrypt?', options: ['Encrypting network traffic', 'Hashing passwords with a salt to prevent rainbow table attacks', 'Generating JWT tokens', 'Compressing files'], answer: 'Hashing passwords with a salt to prevent rainbow table attacks' },
  { domain: 'Backend', category: 'Security', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is rate limiting?', options: ['Limiting internet speed', 'Controlling the number of requests a client can make in a given time window', 'Limiting database query size', 'Setting response time limits'], answer: 'Controlling the number of requests a client can make in a given time window' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the N+1 query problem?', options: ['A query that runs N+1 times due to lazy loading in ORM', 'A SQL syntax error', 'A database with N+1 tables', 'A network timeout issue'], answer: 'A query that runs N+1 times due to lazy loading in ORM' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is eventual consistency in distributed systems?', options: ['All nodes will eventually have the same data, but not necessarily at the same time', 'Data is always consistent', 'A SQL transaction type', 'A database backup strategy'], answer: 'All nodes will eventually have the same data, but not necessarily at the same time' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Advanced', type: 'mcq', question: 'What does ACID stand for in databases?', options: ['Atomicity, Consistency, Isolation, Durability', 'Async, Cached, Indexed, Distributed', 'Atomic, Coded, Integrated, Deployed', 'Access, Control, Integrity, Data'], answer: 'Atomicity, Consistency, Isolation, Durability' },
  { domain: 'Backend', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a circuit breaker pattern?', options: ['Stopping electrical current in servers', 'A design pattern that prevents cascading failures in microservices', 'A code linting rule', 'A database failover mechanism'], answer: 'A design pattern that prevents cascading failures in microservices' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a primary key in a relational database?', options: ['The first column in a table', 'A unique identifier for each row in a table', 'The most important data column', 'A password for the database'], answer: 'A unique identifier for each row in a table' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is an ORM?', options: ['Object-Relational Mapping — tools that let you query databases using objects instead of SQL', 'A REST API standard', 'An online resource manager', 'An optimization method'], answer: 'Object-Relational Mapping — tools that let you query databases using objects instead of SQL' },
  { domain: 'Backend', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is horizontal scaling?', options: ['Making your server taller', 'Adding more servers to distribute load, as opposed to upgrading existing server specs', 'Increasing CPU/RAM of a single server', 'Scaling the database only'], answer: 'Adding more servers to distribute load, as opposed to upgrading existing server specs' },
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the purpose of an HTTP status code 404?', options: ['Server error', 'Unauthorized access', 'Resource not found', 'Request timeout'], answer: 'Resource not found' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a foreign key in a relational database?', options: ['An encrypted key', 'A column that creates a link between two tables by referencing the primary key of another table', 'A secondary index', 'A composite key'], answer: 'A column that creates a link between two tables by referencing the primary key of another table' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the difference between SQL and NoSQL databases?', options: ['SQL is newer', 'SQL uses structured tables with fixed schemas; NoSQL uses flexible data models like documents or key-value pairs', 'NoSQL is always faster', 'SQL cannot handle large data'], answer: 'SQL uses structured tables with fixed schemas; NoSQL uses flexible data models like documents or key-value pairs' },
  { domain: 'Backend', category: 'API Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is idempotency in REST APIs?', options: ['Returning the same response format', 'Making the same request multiple times produces the same result as making it once', 'Using the same authentication method', 'Caching identical responses'], answer: 'Making the same request multiple times produces the same result as making it once' },
  { domain: 'Backend', category: 'Databases', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is database sharding?', options: ['Deleting old database records', 'Partitioning data across multiple database instances to distribute load and improve scalability', 'Backing up a database in fragments', 'Encrypting database columns'], answer: 'Partitioning data across multiple database instances to distribute load and improve scalability' },

  // ─── FULL STACK ───────────────────────────────────────────────────────────────
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the main difference between client-side and server-side rendering?', options: ['Client-side is faster always', 'Client-side renders in browser, server-side renders HTML on the server before sending', 'Server-side uses JavaScript, client-side uses HTML', 'No difference'], answer: 'Client-side renders in browser, server-side renders HTML on the server before sending' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is an API?', options: ['A programming language', 'Application Programming Interface — a contract for how software components communicate', 'A database type', 'A frontend framework'], answer: 'Application Programming Interface — a contract for how software components communicate' },
  { domain: 'Full Stack', category: 'Version Control', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is Git used for?', options: ['Server deployment', 'Version control and tracking code changes', 'Running tests', 'Managing databases'], answer: 'Version control and tracking code changes' },
  { domain: 'Full Stack', category: 'DevOps Basics', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of Docker?', options: ['Version control', 'Containerizing applications for consistent deployment across environments', 'A frontend framework', 'A database'], answer: 'Containerizing applications for consistent deployment across environments' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is WebSocket?', options: ['A web storage API', 'A protocol providing full-duplex communication over a single TCP connection', 'A REST alternative for files', 'A browser API for workers'], answer: 'A protocol providing full-duplex communication over a single TCP connection' },
  { domain: 'Full Stack', category: 'API Design', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is GraphQL?', options: ['A graph database query language', 'A query language and runtime for APIs that allows clients to request exactly the data they need', 'A JavaScript graph library', 'A SQL extension'], answer: 'A query language and runtime for APIs that allows clients to request exactly the data they need' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of a CDN?', options: ['A type of database', 'A geographically distributed network that delivers content quickly to users based on location', 'A programming language', 'An authentication method'], answer: 'A geographically distributed network that delivers content quickly to users based on location' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the CAP theorem?', options: ['A CSS animation principle', 'A distributed systems theorem stating you can only guarantee 2 of: Consistency, Availability, Partition tolerance', 'A caching algorithm', 'A security protocol'], answer: 'A distributed systems theorem stating you can only guarantee 2 of: Consistency, Availability, Partition tolerance' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a microservices architecture?', options: ['Using small JavaScript files', 'Structuring an application as a collection of small, independent services', 'A CSS framework', 'A micro-frontend pattern'], answer: 'Structuring an application as a collection of small, independent services' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is CQRS?', options: ['Command Query Responsibility Segregation — separating read and write operations', 'A caching strategy', 'A CSS reset library', 'A React pattern'], answer: 'Command Query Responsibility Segregation — separating read and write operations' },
  { domain: 'Full Stack', category: 'Security', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is OAuth 2.0?', options: ['A password hashing algorithm', 'An authorization framework allowing third-party services to exchange web resources on behalf of a user', 'A REST standard', 'A JWT replacement'], answer: 'An authorization framework allowing third-party services to exchange web resources on behalf of a user' },
  { domain: 'Full Stack', category: 'Node.js', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the purpose of package.json?', options: ['Storing CSS', 'Defining project metadata, dependencies, and scripts for a Node.js project', 'A JSON database file', 'Configuring the browser'], answer: 'Defining project metadata, dependencies, and scripts for a Node.js project' },
  { domain: 'Full Stack', category: 'Security', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the difference between HTTP and HTTPS?', options: ['HTTPS is faster', 'HTTPS encrypts data in transit using TLS, while HTTP sends data in plain text', 'HTTP is more secure', 'No difference'], answer: 'HTTPS encrypts data in transit using TLS, while HTTP sends data in plain text' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a cookie in web development?', options: ['A tracking pixel', 'A small piece of data stored in the browser, sent with HTTP requests to the server', 'A server-side session object', 'A local database'], answer: 'A small piece of data stored in the browser, sent with HTTP requests to the server' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does SPA stand for?', options: ['Single Page Application', 'Server Page Architecture', 'Static Page App', 'Secure Page Access'], answer: 'Single Page Application' },
  { domain: 'Full Stack', category: 'DevOps Basics', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is CI/CD?', options: ['Code Integration / Code Deployment', 'Continuous Integration / Continuous Delivery — automating build, test, and deployment pipelines', 'Client Interface / Client Design', 'A testing framework'], answer: 'Continuous Integration / Continuous Delivery — automating build, test, and deployment pipelines' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a reverse proxy?', options: ['A client-side proxy', 'A server that sits in front of backend servers, forwarding client requests to them', 'A DNS resolver', 'A load balancer only'], answer: 'A server that sits in front of backend servers, forwarding client requests to them' },
  { domain: 'Full Stack', category: 'DevOps Basics', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of an .env file?', options: ['Storing CSS variables', 'Storing environment-specific configuration and secrets outside of source code', 'A deployment script', 'Configuring the package manager'], answer: 'Storing environment-specific configuration and secrets outside of source code' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is server-sent events (SSE)?', options: ['A REST API pattern', 'A technology where a server pushes real-time updates to the client over a single HTTP connection', 'A WebSocket alternative for bidirectional communication', 'A polling technique'], answer: 'A technology where a server pushes real-time updates to the client over a single HTTP connection' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is eventual consistency?', options: ['Immediate data consistency across all nodes', 'A model where data updates propagate gradually and all nodes will converge to the same state over time', 'Strong consistency in SQL databases', 'A caching invalidation strategy'], answer: 'A model where data updates propagate gradually and all nodes will converge to the same state over time' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the strangler fig pattern?', options: ['A CSS anti-pattern', 'A migration strategy where new functionality gradually replaces legacy code until the old system can be removed', 'A database migration technique', 'A deployment rollback pattern'], answer: 'A migration strategy where new functionality gradually replaces legacy code until the old system can be removed' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a service mesh?', options: ['A microservices UI layer', 'A dedicated infrastructure layer for handling service-to-service communication, observability, and security', 'A message queue topology', 'A network monitoring tool'], answer: 'A dedicated infrastructure layer for handling service-to-service communication, observability, and security' },
  { domain: 'Full Stack', category: 'Web Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is localStorage in the browser?', options: ['Server-side storage', 'A synchronous key-value storage in the browser that persists across sessions', 'A cookie alternative with expiry', 'A React state mechanism'], answer: 'A synchronous key-value storage in the browser that persists across sessions' },
  { domain: 'Full Stack', category: 'DevOps Basics', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a monorepo?', options: ['A single-service repository', 'A single repository containing code for multiple projects or packages', 'A mono-architecture pattern', 'A private npm registry'], answer: 'A single repository containing code for multiple projects or packages' },
  { domain: 'Full Stack', category: 'System Design', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is an API gateway?', options: ['A network firewall', 'A server that acts as the single entry point for clients, routing requests to the appropriate microservices', 'A load balancer', 'An API documentation tool'], answer: 'A server that acts as the single entry point for clients, routing requests to the appropriate microservices' },

  // ─── MOBILE ───────────────────────────────────────────────────────────────────
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is React Native?', options: ['A web framework', 'A framework for building native mobile apps using React and JavaScript', 'A mobile browser', 'An iOS framework'], answer: 'A framework for building native mobile apps using React and JavaScript' },
  { domain: 'Mobile', category: 'Native Development', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the difference between iOS and Android development?', options: ['No difference', 'iOS uses Swift/Objective-C, Android uses Kotlin/Java, with different SDKs and store guidelines', 'iOS uses JavaScript, Android uses Java', 'iOS is faster'], answer: 'iOS uses Swift/Objective-C, Android uses Kotlin/Java, with different SDKs and store guidelines' },
  { domain: 'Mobile', category: 'UI/UX', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a mobile-first design approach?', options: ['Designing only for mobile', 'Starting the design process from mobile screens and progressively enhancing for larger screens', 'Using mobile emulators first', 'Testing on mobile devices first'], answer: 'Starting the design process from mobile screens and progressively enhancing for larger screens' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is Expo in React Native?', options: ['A bundler for web apps', 'A framework and platform for universal React applications that simplifies RN development', 'A testing tool', 'A design system'], answer: 'A framework and platform for universal React applications that simplifies RN development' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is AsyncStorage in React Native?', options: ['An async function wrapper', 'An unencrypted, asynchronous, persistent key-value storage system for React Native', 'A state management library', 'A network caching layer'], answer: 'An unencrypted, asynchronous, persistent key-value storage system for React Native' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is deep linking in mobile apps?', options: ['Linking to deep web content', 'URLs that navigate to a specific screen inside an app', 'Nested navigation', 'External link handling'], answer: 'URLs that navigate to a specific screen inside an app' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the Hermes JavaScript engine in React Native?', options: ['A Node.js runtime', 'A JavaScript engine optimized for React Native that reduces app size and improves startup', 'A native module', 'A testing tool'], answer: 'A JavaScript engine optimized for React Native that reduces app size and improves startup' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the New Architecture in React Native?', options: ['A redesigned UI kit', 'JSI, Fabric, and TurboModules replacing the old bridge architecture for better performance', 'A new navigation system', 'A new state management pattern'], answer: 'JSI, Fabric, and TurboModules replacing the old bridge architecture for better performance' },
  { domain: 'Mobile', category: 'Native Development', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is APK?', options: ['Apple Package Kit', 'Android Package Kit — the file format used by Android for app distribution', 'Application Program Kit', 'Advanced Package Key'], answer: 'Android Package Kit — the file format used by Android for app distribution' },
  { domain: 'Mobile', category: 'Native Development', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the difference between a native and hybrid mobile app?', options: ['No difference', 'Native apps are built with platform-specific languages; hybrid apps use web technologies wrapped in a native container', 'Hybrid apps are faster', 'Native apps work on all platforms'], answer: 'Native apps are built with platform-specific languages; hybrid apps use web technologies wrapped in a native container' },
  { domain: 'Mobile', category: 'Native Development', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is an App Store / Play Store?', options: ['A local app storage', 'Digital distribution platforms for discovering and installing mobile apps on iOS and Android respectively', 'A cloud backup service', 'A mobile browser'], answer: 'Digital distribution platforms for discovering and installing mobile apps on iOS and Android respectively' },
  { domain: 'Mobile', category: 'Native Development', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is push notification in mobile apps?', options: ['A user swipe gesture', "Messages sent from a server to a user's device that appear even when the app is not open", 'An in-app message type', 'A notification permission request'], answer: "Messages sent from a server to a user's device that appear even when the app is not open" },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of React Navigation?', options: ['Animating components', 'A library for managing navigation and routing between screens in React Native apps', 'A map library', 'A gesture handler'], answer: 'A library for managing navigation and routing between screens in React Native apps' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a FlatList in React Native?', options: ['A plain array component', 'A performant component for rendering large scrollable lists efficiently', 'A horizontal scrollview', 'A static list container'], answer: 'A performant component for rendering large scrollable lists efficiently' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the StyleSheet API in React Native?', options: ['A CSS import system', 'A utility that validates and optimizes style objects, similar to CSS but in JavaScript', 'An animation library', 'A theme provider'], answer: 'A utility that validates and optimizes style objects, similar to CSS but in JavaScript' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the difference between Stack and Tab navigation?', options: ['Same thing', 'Stack navigation stacks screens on top of each other; tab navigation switches between screens via bottom/top tabs', 'Tab navigation uses a back button', 'Stack navigation is for iOS only'], answer: 'Stack navigation stacks screens on top of each other; tab navigation switches between screens via bottom/top tabs' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What are native modules in React Native?', options: ['Built-in JavaScript modules', 'Modules written in native code (Swift/Kotlin) that expose platform APIs to JavaScript', 'Core React Native components', 'Third-party npm packages'], answer: 'Modules written in native code (Swift/Kotlin) that expose platform APIs to JavaScript' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is code push (OTA update) in mobile development?', options: ['Pushing code to GitHub', 'Delivering JavaScript bundle updates to users without going through the app store review process', 'A CI/CD pipeline step', 'A hot reload feature'], answer: 'Delivering JavaScript bundle updates to users without going through the app store review process' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is gesture handling in React Native?', options: ['Detecting mouse events', 'Managing touch interactions like swipe, pinch, and pan using libraries like react-native-gesture-handler', 'Keyboard input handling', 'Scroll event management'], answer: 'Managing touch interactions like swipe, pinch, and pan using libraries like react-native-gesture-handler' },
  { domain: 'Mobile', category: 'Native Development', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is IPA in iOS development?', options: ['An Apple account format', 'iOS App Store Package — the file format used to distribute iOS applications', 'An iOS programming API', 'An Xcode project file'], answer: 'iOS App Store Package — the file format used to distribute iOS applications' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is Reanimated in React Native?', options: ['A state management library', 'A library for creating smooth, performant animations that run on the native thread', 'An image animation tool', 'A gesture library'], answer: 'A library for creating smooth, performant animations that run on the native thread' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the bridge architecture in React Native (legacy)?', options: ['A networking layer', 'A serialized asynchronous communication channel between JavaScript and native code', 'A component rendering pipeline', 'A navigation system'], answer: 'A serialized asynchronous communication channel between JavaScript and native code' },
  { domain: 'Mobile', category: 'UI/UX', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a splash screen in mobile apps?', options: ['An error screen', 'A screen displayed while the app loads, typically showing the app logo', 'The app home screen', 'A permission request screen'], answer: 'A screen displayed while the app loads, typically showing the app logo' },
  { domain: 'Mobile', category: 'UI/UX', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is responsive layout in mobile development?', options: ['Layouts that respond to user gestures', 'Designing UIs that adapt to different screen sizes and orientations', 'A fixed-pixel layout', 'An animation technique'], answer: 'Designing UIs that adapt to different screen sizes and orientations' },
  { domain: 'Mobile', category: 'React Native', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the purpose of the Metro bundler in React Native?', options: ['A deployment tool', 'The JavaScript bundler that transforms and serves JS code to the React Native runtime', 'A native module compiler', 'A testing runner'], answer: 'The JavaScript bundler that transforms and serves JS code to the React Native runtime' },

  // ─── DATA SCIENCE ─────────────────────────────────────────────────────────────
  { domain: 'Data Science', category: 'Pandas/NumPy', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a DataFrame in pandas?', options: ['A Python list', 'A 2-dimensional labeled data structure with columns of potentially different types', 'A database table wrapper', 'A NumPy array alias'], answer: 'A 2-dimensional labeled data structure with columns of potentially different types' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the purpose of data normalization?', options: ['Removing data', 'Scaling data to a standard range to prevent features with large values from dominating', 'Sorting data', 'Backing up data'], answer: 'Scaling data to a standard range to prevent features with large values from dominating' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is overfitting in machine learning?', options: ['Using too much data', 'A model that performs well on training data but poorly on unseen data', 'Training a model too slowly', 'Using the wrong algorithm'], answer: 'A model that performs well on training data but poorly on unseen data' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is cross-validation?', options: ['Validating data across teams', 'A technique for evaluating models by training and testing on different subsets of data', 'Comparing two models', 'A data cleaning method'], answer: 'A technique for evaluating models by training and testing on different subsets of data' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the bias-variance tradeoff?', options: ['Balancing hardware bias vs variance', 'The tension between model underfitting (high bias) and overfitting (high variance)', 'Choosing between accuracy and speed', 'Selecting training data'], answer: 'The tension between model underfitting (high bias) and overfitting (high variance)' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What does PCA stand for?', options: ['Principal Component Analysis', 'Primary Cluster Algorithm', 'Predictive Classification Array', 'Probabilistic Cluster Analysis'], answer: 'Principal Component Analysis' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is gradient descent?', options: ['A database optimization', 'An iterative optimization algorithm that minimizes a loss function by moving in the direction of steepest descent', 'A data processing technique', 'A neural network type'], answer: 'An iterative optimization algorithm that minimizes a loss function by moving in the direction of steepest descent' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the difference between L1 and L2 regularization?', options: ['L1 adds absolute value penalty (can zero out weights/feature selection), L2 adds squared penalty (shrinks weights)', 'L1 is for linear models, L2 for neural networks', 'L1 is faster, L2 is slower', 'No real difference'], answer: 'L1 adds absolute value penalty (can zero out weights/feature selection), L2 adds squared penalty (shrinks weights)' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a confusion matrix?', options: ['A matrix that confuses the model', 'A table showing true positives, false positives, true negatives, and false negatives for a classifier', 'A complex dataset', 'A visualization tool'], answer: 'A table showing true positives, false positives, true negatives, and false negatives for a classifier' },
  { domain: 'Data Science', category: 'Pandas/NumPy', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is NumPy used for in Python?', options: ['Web scraping', 'Efficient numerical computing with multi-dimensional arrays and mathematical operations', 'Data visualization', 'Database querying'], answer: 'Efficient numerical computing with multi-dimensional arrays and mathematical operations' },
  { domain: 'Data Science', category: 'Pandas/NumPy', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the purpose of Matplotlib?', options: ['Machine learning modeling', 'A Python library for creating static, animated, and interactive visualizations', 'Data cleaning', 'Feature engineering'], answer: 'A Python library for creating static, animated, and interactive visualizations' },
  { domain: 'Data Science', category: 'Pandas/NumPy', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a null value in a dataset?', options: ['A value of zero', 'A missing or undefined value in a dataset that must be handled before modeling', 'A negative number', 'An outlier'], answer: 'A missing or undefined value in a dataset that must be handled before modeling' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is feature engineering?', options: ['Building software features', 'The process of creating or transforming input variables to improve model performance', 'Selecting the best model', 'Tuning hyperparameters'], answer: 'The process of creating or transforming input variables to improve model performance' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a decision tree?', options: ['A file system diagram', 'A supervised learning model that splits data into branches based on feature conditions to make predictions', 'An unsupervised clustering method', 'A neural network layer'], answer: 'A supervised learning model that splits data into branches based on feature conditions to make predictions' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of train/validation/test split?', options: ['Splitting data for parallel processing', 'Separating data for training, tuning hyperparameters, and final unbiased evaluation respectively', 'Distributing data across servers', 'A data backup strategy'], answer: 'Separating data for training, tuning hyperparameters, and final unbiased evaluation respectively' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is clustering in unsupervised learning?', options: ['Labeling data groups', 'Grouping similar data points together without predefined labels', 'A supervised classification method', 'Sorting data alphabetically'], answer: 'Grouping similar data points together without predefined labels' },
  { domain: 'Data Science', category: 'Deep Learning', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a convolutional neural network (CNN)?', options: ['A text processing network', 'A deep learning architecture designed for processing grid-like data such as images using convolutional layers', 'A recurrent network type', 'A clustering algorithm'], answer: 'A deep learning architecture designed for processing grid-like data such as images using convolutional layers' },
  { domain: 'Data Science', category: 'Deep Learning', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the purpose of dropout in neural networks?', options: ['Removing nodes permanently', 'A regularization technique that randomly deactivates neurons during training to prevent overfitting', 'Reducing model size', 'Speeding up training'], answer: 'A regularization technique that randomly deactivates neurons during training to prevent overfitting' },
  { domain: 'Data Science', category: 'Deep Learning', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is transfer learning?', options: ['Moving data between servers', 'Reusing a pre-trained model on a new but related task, reducing training time and data requirements', 'A data migration technique', 'A model compression method'], answer: 'Reusing a pre-trained model on a new but related task, reducing training time and data requirements' },
  { domain: 'Data Science', category: 'Statistics', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is the mean of a dataset?', options: ['The most frequent value', 'The middle value when sorted', 'The sum of all values divided by the count', 'The difference between max and min'], answer: 'The sum of all values divided by the count' },
  { domain: 'Data Science', category: 'Statistics', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is an outlier?', options: ['A missing value', 'A data point that differs significantly from other observations in the dataset', 'A duplicate record', 'A categorical variable'], answer: 'A data point that differs significantly from other observations in the dataset' },
  { domain: 'Data Science', category: 'Statistics', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a correlation coefficient?', options: ['A measure of model accuracy', 'A statistical measure of the linear relationship between two variables, ranging from -1 to 1', 'A clustering metric', 'A loss function value'], answer: 'A statistical measure of the linear relationship between two variables, ranging from -1 to 1' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is hyperparameter tuning?', options: ['Adjusting model weights during training', 'The process of finding the optimal configuration settings of a model that are not learned from data', 'Normalizing input features', 'Splitting training data'], answer: 'The process of finding the optimal configuration settings of a model that are not learned from data' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is one-hot encoding?', options: ['Encrypting categorical data', 'Converting categorical variables into binary vectors where each category becomes a separate column', 'A hashing technique', 'Label encoding'], answer: 'Converting categorical variables into binary vectors where each category becomes a separate column' },
  { domain: 'Data Science', category: 'ML Fundamentals', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is an ROC curve?', options: ['A training loss curve', 'A graph showing the trade-off between true positive rate and false positive rate at various classification thresholds', 'A model comparison chart', 'A data distribution plot'], answer: 'A graph showing the trade-off between true positive rate and false positive rate at various classification thresholds' },

  // ─── DEVOPS ───────────────────────────────────────────────────────────────────
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is CI/CD?', options: ['A programming language', 'Continuous Integration/Continuous Deployment — automating build, test, and deployment pipelines', 'A cloud provider', 'A version control system'], answer: 'Continuous Integration/Continuous Deployment — automating build, test, and deployment pipelines' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is Docker Compose?', options: ['A Docker UI tool', 'A tool for defining and running multi-container Docker applications', 'A Docker registry', 'A Docker monitoring tool'], answer: 'A tool for defining and running multi-container Docker applications' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is Infrastructure as Code (IaC)?', options: ['Writing code inside infrastructure', 'Managing and provisioning infrastructure through machine-readable definition files', 'A cloud service', 'A deployment strategy'], answer: 'Managing and provisioning infrastructure through machine-readable definition files' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is Kubernetes?', options: ['A programming language', 'An open-source container orchestration system for automating deployment, scaling, and management of containers', 'A monitoring tool', 'A CI/CD platform'], answer: 'An open-source container orchestration system for automating deployment, scaling, and management of containers' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a Kubernetes Pod?', options: ['A group of nodes', 'The smallest deployable unit in Kubernetes, containing one or more containers', 'A cluster namespace', 'A deployment strategy'], answer: 'The smallest deployable unit in Kubernetes, containing one or more containers' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is Terraform?', options: ['A Linux distribution', 'An IaC tool for building, changing, and versioning infrastructure across cloud providers', 'A monitoring solution', 'A containerization tool'], answer: 'An IaC tool for building, changing, and versioning infrastructure across cloud providers' },
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is the GitOps pattern?', options: ['Using Git to track bugs', 'Using Git as the single source of truth for infrastructure and application deployment', 'Git-based CI/CD only', 'Open source Git practices'], answer: 'Using Git as the single source of truth for infrastructure and application deployment' },
  { domain: 'DevOps', category: 'Monitoring', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is observability in distributed systems?', options: ['Monitoring dashboards', 'The ability to understand internal system state from external outputs: metrics, logs, and traces', 'Access control', 'Performance optimization'], answer: 'The ability to understand internal system state from external outputs: metrics, logs, and traces' },
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a blue-green deployment?', options: ['Using two colors in dashboards', 'A release strategy using two identical environments; traffic switches between them to minimize downtime', 'A Git branching strategy', 'A database migration strategy'], answer: 'A release strategy using two identical environments; traffic switches between them to minimize downtime' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a load balancer?', options: ['A server weight measurement tool', 'A device or service that distributes incoming network traffic across multiple servers', 'A CPU management tool', 'A database optimizer'], answer: 'A device or service that distributes incoming network traffic across multiple servers' },
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is version control?', options: ['Tracking software version numbers', 'A system that records changes to files over time so you can recall specific versions later', 'An automated deployment tool', 'A dependency manager'], answer: 'A system that records changes to files over time so you can recall specific versions later' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is a container in software?', options: ['A database storage unit', 'A lightweight, portable package that includes everything needed to run an application', 'A virtual machine', 'A cloud storage bucket'], answer: 'A lightweight, portable package that includes everything needed to run an application' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Beginner', type: 'mcq', question: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Program Utility', 'Core Processing Unit', 'Central Program Unit'], answer: 'Central Processing Unit' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a Kubernetes Pod?', options: ['A cluster of nodes', 'The smallest deployable unit in Kubernetes, containing one or more containers', 'A Kubernetes service', 'A namespace partition'], answer: 'The smallest deployable unit in Kubernetes, containing one or more containers' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is infrastructure as code (IaC)?', options: ['Writing code for infrastructure companies', 'Managing and provisioning infrastructure through machine-readable config files rather than manual processes', 'A cloud billing model', 'An on-premise deployment strategy'], answer: 'Managing and provisioning infrastructure through machine-readable config files rather than manual processes' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is the purpose of Terraform?', options: ['A container runtime', 'An IaC tool that lets you define cloud infrastructure in configuration files and provision it across providers', 'A CI/CD platform', 'A Kubernetes manager'], answer: 'An IaC tool that lets you define cloud infrastructure in configuration files and provision it across providers' },
  { domain: 'DevOps', category: 'Monitoring', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is log aggregation?', options: ['Counting log lines', 'Collecting and centralizing logs from multiple services into a single system for analysis', 'Compressing log files', 'Deleting old logs'], answer: 'Collecting and centralizing logs from multiple services into a single system for analysis' },
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is an artifact in CI/CD?', options: ['A legacy code file', 'A build output (binary, Docker image, package) produced by a pipeline and stored for deployment', 'A test report', 'A pipeline stage'], answer: 'A build output (binary, Docker image, package) produced by a pipeline and stored for deployment' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a Helm chart?', options: ['A Kubernetes dashboard', 'A package manager format for Kubernetes that bundles templates for deploying applications', 'A CI/CD pipeline template', 'A Docker compose equivalent'], answer: 'A package manager format for Kubernetes that bundles templates for deploying applications' },
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is a rolling deployment?', options: ['Deploying in alphabetical order', 'Gradually replacing old instances with new ones, reducing downtime by keeping some instances running throughout', 'A blue-green deployment', 'A manual deployment process'], answer: 'Gradually replacing old instances with new ones, reducing downtime by keeping some instances running throughout' },
  { domain: 'DevOps', category: 'Monitoring', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is SLO (Service Level Objective)?', options: ['A service contract with users', 'A target value for a service reliability metric, such as 99.9% uptime', 'An error budget', 'A monitoring threshold'], answer: 'A target value for a service reliability metric, such as 99.9% uptime' },
  { domain: 'DevOps', category: 'Infrastructure', phase: 1, level: 'Beginner', type: 'mcq', question: 'What is SSH?', options: ['A file transfer protocol', 'Secure Shell — a cryptographic protocol for securely accessing and managing remote servers', 'A web server', 'A deployment tool'], answer: 'Secure Shell — a cryptographic protocol for securely accessing and managing remote servers' },
  { domain: 'DevOps', category: 'Monitoring', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a health check in DevOps?', options: ['A server hardware inspection', 'An automated probe that verifies a service is running and responding correctly', 'A security audit', 'A performance benchmark'], answer: 'An automated probe that verifies a service is running and responding correctly' },
  { domain: 'DevOps', category: 'CI/CD', phase: 1, level: 'Advanced', type: 'mcq', question: 'What is GitOps?', options: ['Using Git for coding only', 'A practice where the entire system state is defined declaratively in Git, with automated reconciliation to the live environment', 'A Git branching strategy', 'A CI/CD tool'], answer: 'A practice where the entire system state is defined declaratively in Git, with automated reconciliation to the live environment' },
  { domain: 'DevOps', category: 'Docker & Kubernetes', phase: 1, level: 'Intermediate', type: 'mcq', question: 'What is a secret in Kubernetes?', options: ['A hidden namespace', 'An object that stores sensitive data like passwords, tokens, or keys, keeping them out of pod specs', 'An encrypted ConfigMap', 'A private container image'], answer: 'An object that stores sensitive data like passwords, tokens, or keys, keeping them out of pod specs' },
]

async function main() {
  console.log('🌱 Starting seed...')

  // Create admin user
  const adminPassword = await bcrypt.hash('Admin@1234', 12)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@devcert.io' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@devcert.io',
      password: adminPassword,
      username: 'admin',
      role: 'admin',
      isEmailVerified: true,
    }
  })
  console.log(`✅ Admin user: ${admin.email}`)

  // Create demo user
  const demoPassword = await bcrypt.hash('Demo@1234', 12)
  const demo = await prisma.user.upsert({
    where: { email: 'demo@devcert.io' },
    update: {},
    create: {
      name: 'Demo User',
      email: 'demo@devcert.io',
      password: demoPassword,
      username: 'demouser1',
      isEmailVerified: true,
    }
  })
  console.log(`✅ Demo user: ${demo.email}`)

  // Seed question bank
  await prisma.questionBank.deleteMany({})
  const created = await prisma.questionBank.createMany({ data: questions })
  console.log(`✅ Seeded ${created.count} questions`)

  // Seed testimonials
  await prisma.testimonial.deleteMany({})
  await prisma.testimonial.createMany({
    data: [
      { name: 'Aditya Kumar',  role: 'Frontend Developer', text: 'The AI feedback was incredibly detailed. Found 3 security issues I completely missed. Got my first job using the certificate!', stars: 5, order: 0 },
      { name: 'Priya Sharma',  role: 'Backend Engineer',   text: 'The proctored exam proved my skills to employers way more convincingly than just listing technologies on my resume.',          stars: 5, order: 1 },
      { name: 'Rohan Mehta',   role: 'Full Stack Dev',     text: 'Submitted my portfolio project and got a 82/100 score with super detailed feedback. Worth every rupee of the premium plan.',   stars: 5, order: 2 },
      { name: 'Sneha Iyer',    role: 'React Developer',    text: 'DevCert helped me stand out in a crowded market. The certificate with a verification URL is something no other platform offers.', stars: 5, order: 3 },
      { name: 'Vikram Singh',  role: 'Node.js Developer',  text: "The AI caught architectural issues I didn't even consider. My code quality has genuinely improved after reading the feedback.",   stars: 5, order: 4 },
    ]
  })
  console.log('✅ Seeded testimonials')

  console.log('🎉 Seed complete!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())